language: go

sudo: false

go:
    - 1.8.x
    - tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/gitbin | DEST=$HOME/bin bash
    - gitbin get Masterminds/glide 0.12.3 -o $HOME/bin
    - make envcheck

before_script: make install || true

script: make check
