language: go

sudo: false

go:
    - 1.8.x
    - tip

matrix:
    allow_failures:
        - go: tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL http://get.binhq.io/gitbin | DEST=$HOME/bin bash
    - gitbin get Masterminds/glide 0.12.3 -o $HOME/bin

before_script: glide install

script:
    - go test
    - gofmt -l $(find . -type f -name "*.go" -not -path "./vendor/*") | read something && echo "Code differs from gofmt's style" 1>&2 && exit 1 || true
